spring:
  datasource:
    url: jdbc:postgresql://postgresdb:5432/authdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

flyway:
  baseline-on-migrate: true
  locations: classpath:db/migration
  enabled: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
